Fix pandoc and variables

diff --git a/.github/workflows/convert_and_upload.yml b/.github/workflows/convert_and_upload.yml
--- a/.github/workflows/convert_and_upload.yml
+++ b/.github/workflows/convert_and_upload.yml
@@ -18,29 +18,32 @@ jobs:
   convert_via_pandoc:
     # The type of runner that the job will run on
     runs-on: ubuntu-latest
-
+    env:
+      INPUT: README.md
+      OUTPUT: README.docx
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v4
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
-      - uses: docker://pandoc/core:2.9
-        with:
-          args: >- 
-            --standalone
-            --output=README.docx
-            README.md
-      # Runs a single command using the runners shell
-      - name: Run a one-line script
-        run: echo Hello, world!
+      - uses: pandoc/actions/setup@v1
+      - name: Convert .md to Word
+        run: |
+          # Run pandoc in verbose mode and capture output
+          set -o pipefail
+          pandoc --standalone --verbose --output="$OUTPUT" "$INPUT" 2>&1 | tee pandoc.log
+          if grep -q "image not found" pandoc.log; then
+            echo "❌ Pandoc could not find the image."
+            exit 1
+          fi
 
       # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
+      - name: Commit and Push
         run: |
           git config user.name "github-actions[bot]"
           git config user.email "github-actions[bot]@users.noreply.github.com"
           git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/DamianS-eng/Mario-Kart-64-HD.git
-          git add README.docx
+          git add "$OUTPUT"
           git commit -am "update word"
           git push
